title = "gitleaks config"

[allowlist]
description = "Allow known false-positives in public test-vector markdown"
regexTarget = "line"
paths = [
  '''^test_vectors/vectors\.md$''',
  '''^previous_versions/v[0-9]+\.[0-9]+\.[0-9]+/test_vectors/vectors\.md$''',
]
regexes = [
  '''Compressed (public key|pubkey)''',
]

